"""add_findings_fixes_chains_graph_columns

Revision ID: 1ea1844bd656
Revises: 
Create Date: 2026-02-27 20:30:36.751045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1ea1844bd656'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('findings', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('fixes', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('chains', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('graph_nodes', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('graph_edges', sa.JSON(), nullable=True))
    op.add_column('analyses', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'error_message')
    op.drop_column('analyses', 'graph_edges')
    op.drop_column('analyses', 'graph_nodes')
    op.drop_column('analyses', 'chains')
    op.drop_column('analyses', 'fixes')
    op.drop_column('analyses', 'findings')
    # ### end Alembic commands ###
